spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb
    username: riskuser
    password: riskpass
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: risk-scoring-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
server:
  port: 8081
app:
  kafka:
    topic:
      transactions: transactions-risk
  data-generator:
    enabled: true
logging:
  level:
    com.riskengine: DEBUG