jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      docker:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Integration Tests
        run: ./mvnw clean verify -Dtest=*IT
